name: mitocloud-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas  # MOVED HERE
  - numpy   # MOVED HERE
  - scikit-learn # MOVED HERE
  - pip
  - pip:
    - mlflow
    - azure-identity
    - azure-storage-blob
    - joblib
